let a="+------------------------------------------------------+";
let m="|           🅿 🆁 🅾 🅶 🆁 🅴 🆂 🆂   🆁 🅴 🅿 🅾 🆁 🆃              |";
let b="|                                                      |";
let c="|  𝙉 𝘼 𝙈 𝙀        :    Leeladhar J                     |";
let d="|  𝙎 𝘾 𝙃 𝙊 𝙊 𝙇     :    D.P.N.Z.P. High School         |";
let e="|  𝙂 𝙍 𝘼 𝘿 𝙀       :    Class 10                       |";
var f="|  𝙎 𝙀 𝘾 𝙏 𝙄 𝙊 𝙉    :    A                             |";
var g="|  𝙍 𝙊 𝙇 𝙇  𝙉𝙊      :    54                            |";
var h="|  S̲ U̲ B̲ J̲ E̲ C̲ T̲ S̲        M̲ A̲ R̲ K̲ S̲                    |"
const i="|  * Mathematics    =       𝟡 𝟙                        |";
const j="|  * Telugu         =       𝟡 𝟝                        |";
const k="|  * Science        =       𝟡 𝟟                        |";
let l="|   Teacher's sign                  Parent's sign      |";
console.log(a);
console.log(b);
console.log(m);
console.log(b);
console.log(b);
console.log(c);
console.log(b);
console.log(d);
console.log(b);
console.log(e);
console.log(b);
console.log(f);
console.log(b);
console.log(g);
console.log(b);
console.log(a);
console.log(b);
console.log(h);
console.log(b);
console.log(i);
console.log(b);
console.log(j);
console.log(b);
console.log(k);
console.log(b);
console.log(b)
console.log(b);
console.log(l);
console.log(a);